layout_spectrum: 0.4114440237272457
typography_spectrum: 0.672300569900579
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.36766864152957157
  lightness: 0.7017643670417774
  saturation: 0.005030565526299547
  rhythmicContrast: 0.5224104021826187
name: Open the Sauce
logo: null
opengraph:
  type: ''
  appId: ''
title: technocratic tabasco sauce
description: Mix 100ml of Open Source with 2 tonnes of WTF happened here
author:
  name: Deimos
  url: openthesauce.com
  email: deimos@openthesauce.com
content_rating:
  adult: false
navigation:
  - name: WTF is this site?
    id: 8cfc834d-0b42-4224-b644-301bbfbdb0f1
    type: content
content: []
github: true
