layout_spectrum: 0.7321454794816489
typography_spectrum: 0.1257054302207941
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.7860928427028737
  lightness: 0.3596603622544778
  saturation: 0.8468458490313427
  rhythmicContrast: 0.5525433134149281
name: Open the Sauce
logo: null
opengraph:
  type: ''
  appId: ''
title: technocratic tabasco sauce
description: Mix 100ml of Open Source with 2 tonnes of WTF happened here
author:
  name: Deimos
  url: openthesauce.com
  email: deimos@openthesauce.com
content_rating:
  adult: false
navigation:
  - name: WTF is this site?
    id: 8cfc834d-0b42-4224-b644-301bbfbdb0f1
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F100785455&url=https%3A%2F%2Fplayer.vimeo.com%2F100785455%3Floop%3D1&image=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F482375085_1280.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=vimeo"
      width="1000" height="563" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: seccovan
          url: 'https://vimeo.com/seccovan'
          avatar: {}
      related: []
      publisher:
        url: 'https://vimeo.com/'
        name: Vimeo
        favicon: 'https://player.vimeo.com/favicon.ico'
        domain: player.vimeo.com
      keywords: []
      description: >-
        For licensing/usage please contact: licensing(at)jukinmediadotcom MAKING
        OF : http://vimeo.com/102935595 More at:
        http://www.behance.net/gallery/18362139/FUTURAMA-3D-part-1 Music: Alan
        Silvestri - "Forrest Gump Suite" (fragment) Software: 3dsmax, Nuke,
        Photoshop, After Effects Tools : Multiscatter plugin, Ghost Town script,
        Poly FX script
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: 'https://player.vimeo.com/100785455?loop=1'
      title: Futurama 3d (test shot)
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
purpose:
  - type: internal
    label: Get in touch
    item: 860e3dc4-b3b9-48bb-aead-61e161e0cf1c
